<!--page_container-->
    <div class="page_container">
    	<div class="wrap">
        	<div class="breadcrumb">
				<div>
					<a href="index.html">Home</a><span>/</span>About
				</div>
			</div>
			<div class="container">
                <section>
                    <div class="row">
                        <div class="span4">
                            <h2 class="title"><span>Our Process</span></h2>
                            <p>Be on site to provide a free estimate for the project. Always inspect the work right 
                            after the project is complete to ensure it meets customer requirements. Guarantee our works.   
                            </p>
                                                   
                        </div>
                        <div class="span4">
                            <h2 class="title"><span>Our Mission</span></h2>
                        	<p>Doan landscaping provides excellent services to customers around the Puget Sound area. We offer a full range of services to meet your landscaping needs. 
                        	Please see our services section to learn more about our excellent services.</p>
                        </div>
                        <div class="span4">
                            <h2 class="title"><span>What We Do</span></h2>
                        	<p>Provide lawn care, exterior design, yard work, landscape design with best quality and 100% customer satisfaction.</p>
                        	<p>Please call Toi Doan 425 772 9499 / 425 770 7021 for a free estimate.</p>
                             
                        </div>                        
                    </div>
                </section>
                <section>
                	<h2 class="title"><span>Our Team</span></h2>
                    <!--<p>Enim ultrices, elementum phasellus. Mauris sed nulla sed, egestas feugiat a dictum libero, nunc sapien tristique facilisis venenatis risus, suspendisse ac nec et. Nulla sed mauris, congue duis proin nonummy adipiscing vitae interdum. Augue eget ultrices tempor, dignissim et libero. Arcu quis, arcu et mauris molestie auctor aliquam, ut vitae, turpis ac rhoncus mi sagittis arcu, ut a nullam donec.</p>-->
                	<div class="row">
                        <div class="span3">                            
                            <div class="profile">
                            	<img alt="" src="images/team/team1.png">
                                <h4>Team Pictures</h4>
                                <div class="profile_title">Toi and team members</div>
                                <p>On break while building a retaining wall for one of our customers.</p>
                            </div>
                        </div>
                        <div class="span3">
                            <div class="profile">
                            	<img alt="" src="images/team/team2.png">
                                <h4>Team Pictures</h4>
                                <div class="profile_title">Work hard</div>
                                <p>Started putting foundation for the retaining wall.</p>
                            </div>
                        </div>
                        <div class="span3">
                            <div class="profile">
                            	<img alt="" src="images/team/team3.png">
                                <h4>Team Pictures</h4>
                                <div class="profile_title">Almost done</div>
                                <p>Putting up retaining wall...</p>
                            </div>
                        </div>
                        <div class="span3">
                            <div class="profile">
                            	<img alt="" src="images/team/team2.png">
                                <h4>Team Pictures</h4>
                                <div class="profile_title">Our team at work</div>
                                <p>Another view ...</p>
                            </div>
                        </div>                        
                    </div>
                </section>
            </div>
        </div>
    </div>
    <!--//page_container-->
