<!--page_container-->
		<div class="page_container">
			<div class="container">
				<!--slider-->
				<div id="main_slider">
					<div class="camera_wrap" id="camera_wrap_1">
						<div data-src="images/slider/slide1.jpg">
							<div class="camera_caption fadeFromBottom">
								<div class="slide_descr">
									<b>build your own</b></br>
									<span>well-appointed</span> living space
								</div>
								<div class="slider_next"><span></span></div>
								<div class="slider_prev"><span></span></div>
							</div>
						</div>
						<div data-src="images/slider/slide2.jpg">
							<div class="camera_caption fadeFromBottom">
								<div class="slide_descr">
									<b>Lorem ipsum dolor</b></br>
									sit amet, <span>consectetur</span> adipisicing
								</div>
								<div class="slider_next"><span></span></div>
								<div class="slider_prev"><span></span></div>
							</div>
						</div>
						<div data-src="images/slider/slide3.jpg">
							<div class="camera_caption fadeFromBottom">
								<div class="slide_descr">
									<b><span>Sed ut perspiciatis</span></b></br>
									unde omnis iste natus error sit
								</div>
								<div class="slider_next"><span></span></div>
								<div class="slider_prev"><span></span></div>
							</div>
						</div>
					</div><!-- #camera_wrap_1 -->
					<div class="clear"></div>	
				</div>
				<!--//slider-->
			</div>
			
			<!--Recent Gallery-->
			<div class="wrap recent_gal_block">
				<div class="container">
					<h2 class="title">Featured content</h2>
					<ul class="row">
						<li class="span4">
							<div class="proj_block">
								<img src="images/featured_works/1.jpg" alt="" />
								<a href="images/featured_works/1.jpg" rel="prettyPhoto[portfolio1]"><span class="portfolio_zoom1"></span></a>
								<div class="proj_descr">
									<p>lorem ipsum</p>
									Etiam pulvinar felis in lacus adipiscing semper. Proin sodales et eros et sodales.
								</div>
							</div>
						</li>
						<li class="span4">
							<div class="proj_block">
								<img src="images/featured_works/2.jpg" alt="" />
								<a href="images/featured_works/2.jpg" rel="prettyPhoto[portfolio1]"><span class="portfolio_zoom1"></span></a>
								<div class="proj_descr">
									<p>lorem ipsum</p>
									Etiam pulvinar felis in lacus adipiscing semper. Proin sodales et eros et sodales.
								</div>
							</div>
						</li>
						<li class="span4">
							<div class="proj_block">
								<img src="images/featured_works/3.jpg" alt="" />
								<a href="images/featured_works/3.jpg" rel="prettyPhoto[portfolio1]"><span class="portfolio_zoom1"></span></a>
								<div class="proj_descr">
									<p>lorem ipsum</p>
									Etiam pulvinar felis in lacus adipiscing semper. Proin sodales et eros et sodales.
								</div>
							</div>
						</li>
						<div class="clear"></div>
					</ul>
				</div>
			</div>
			<!--//Recent Gallery-->
			
			<!--Welcome-->
			<div class="wrap welcome_bg">
				<div class="container">
					<div class="welcome_block">
						<p><span>Creative ideas</span> for your garden</p>
						Phasellus adipiscing odio ac nisl fringilla sollicitudin. Donec non adipiscing nulla, quis feugiat lorem. Duis mattis ultricies
					</div>
				</div>
			</div>
			<!--//Welcome-->
			
			<!--planning-->
			<div class="wrap planning">
				<div class="container">
					<div class="row">
						<a class="span3" href="javascript:void(0);">
							<span class="service_block">
								<span class="icon_block">
									<img class="icon1" src="images/icon1.png" />
									<img class="icon1_h" src="images/icon1_h.png" />
								</span>
								<span class="link_title">Consultation</span>
								<span class="service_txt">Donec euismod risus tortor, quis sodales lorem malesuada eget. Duis vel blandit lorem. Integer</span>
							</span>
						</a>
						<a class="span3" href="javascript:void(0);">
							<span class="service_block">
								<span class="icon_block">
									<img class="icon1" src="images/icon2.png" />
									<img class="icon1_h" src="images/icon2_h.png" />
								</span>
								<span class="link_title">Planting Design</span>
								<span class="service_txt">Donec euismod risus tortor, quis sodales lorem malesuada eget. Duis vel blandit lorem. Integer</span>
							</span>
						</a>
						<a class="span3" href="javascript:void(0);">
							<span class="service_block">
								<span class="icon_block">
									<img class="icon1" src="images/icon3.png" />
									<img class="icon1_h" src="images/icon3_h.png" />
								</span>
								<span class="link_title">Installation</span>
								<span class="service_txt">Donec euismod risus tortor, quis sodales lorem malesuada eget. Duis vel blandit lorem. Integer</span>
							</span>
						</a>
						<a class="span3" href="javascript:void(0);">
							<span class="service_block">
								<span class="icon_block">
									<img class="icon1" src="images/icon4.png" />
									<img class="icon1_h" src="images/icon4_h.png" />
								</span>
								<span class="link_title">Installation</span>
								<span class="service_txt">Donec euismod risus tortor, quis sodales lorem malesuada eget. Duis vel blandit lorem. Integer</span>
							</span>
						</a>
						<div class="clear"></div>
					</div>
				</div>
			</div>
			<!--//planning-->
			
			<!--Latest news-->
			<div class="wrap">
				<div class="container">
					<h2 class="title">testimonials</h2>
					<div id="testim_carousel" class="carousel slide">
						<div class="row carousel-inner">
							<div class="item active">
								<div class="span6 testim_block">
									<div class="testim_block_txt">
										Donec euismod risus tortor, quis sodales lorem malesuada eget. Duis vel blandit lorem. Integer pellentesque suscipit tortor quis sollicitudin. Morbi eget sem porttitor, cursus lorem sed, molestie libero.
									</div>
									<div class="testim_author">John Doe, <a href="javascript:void(0);">http://demolink.org</a></div>
								</div>
								<div class="span6 testim_block">
									<div class="testim_block_txt">
										Donec euismod risus tortor, quis sodales lorem malesuada eget. Duis vel blandit lorem. Integer pellentesque suscipit tortor quis sollicitudin. Morbi eget sem porttitor, cursus lorem sed, molestie libero.
									</div>
									<div class="testim_author">John Doe, <a href="javascript:void(0);">http://demolink.org</a></div>
								</div>
								<div class="clear"></div>
							</div>
							<div class="item">
								<div class="span6 testim_block">
									<div class="testim_block_txt">
										Donec euismod risus tortor, quis sodales lorem malesuada eget. Duis vel blandit lorem. Integer pellentesque suscipit tortor quis sollicitudin. Morbi eget sem porttitor, cursus lorem sed, molestie libero.
									</div>
									<div class="testim_author">John Doe, <a href="javascript:void(0);">http://demolink.org</a></div>
								</div>
								<div class="span6 testim_block">
									<div class="testim_block_txt">
										Donec euismod risus tortor, quis sodales lorem malesuada eget. Duis vel blandit lorem. Integer pellentesque suscipit tortor quis sollicitudin. Morbi eget sem porttitor, cursus lorem sed, molestie libero.
									</div>
									<div class="testim_author">John Doe, <a href="javascript:void(0);">http://demolink.org</a></div>
								</div>
								<div class="clear"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--Latest news-->

		</div>
		<!--//page_container-->
