<!--page_container-->
		<div class="page_container">
			<div class="container">
				<!--slider-->
				<div id="main_slider">
					<div class="camera_wrap" id="camera_wrap_1">
						<div data-src="images/slider/landscaping1.png">
							<div class="camera_caption fadeFromBottom">
								<div class="slide_descr">
									<b>build a beautiful fish pond</b></br>
									<span>in your back yard</span>
								</div>
								<div class="slider_next"><span></span></div>
								<div class="slider_prev"><span></span></div>
							</div>
						</div>
						<div data-src="images/slider/landscaping2.png">
							<div class="camera_caption fadeFromBottom">
								<div class="slide_descr">
									<b>Building a retaining wall is hard</b></br>
									<span>but we can help</span> 
								</div>
								<div class="slider_next"><span></span></div>
								<div class="slider_prev"><span></span></div>
							</div>
						</div>
						<div data-src="images/slider/landscaping3.png">
							<div class="camera_caption fadeFromBottom">
								<div class="slide_descr">
									<b><span>Landscaping your home</span></b></br>
									Please call us for free estimate
								</div>
								<div class="slider_next"><span></span></div>
								<div class="slider_prev"><span></span></div>
							</div>
						</div>
					</div><!-- #camera_wrap_1 -->
					<div class="clear"></div>	
				</div>
				<!--//slider-->
			</div>
			
			<!--Recent Gallery-->
			<div class="wrap recent_gal_block">
				<div class="container">
					<h2 class="title">Featured content</h2>
					<ul class="row">
						<li class="span4">
							<div class="proj_block">
								<img src="images/featured_works/garden-maintenance.jpg" alt="" />
								<a href="images/featured_works/garden-maintenance.jpg" rel="prettyPhoto[portfolio1]"><span class="portfolio_zoom1"></span></a>
								<div class="proj_descr">
									<p>Gardening maintenance.</p>
									Gardening maintenance.
								</div>
							</div>
						</li>
						<li class="span4">
							<div class="proj_block">
								<img src="images/featured_works/landscape-design.jpg" alt="" />
								<a href="images/featured_works/landscape-design.jpg" rel="prettyPhoto[portfolio1]"><span class="portfolio_zoom1"></span></a>
								<div class="proj_descr">
									<p>Landscaping Design Work.</p>
									Landscaping Design Work.
								</div>
							</div>
						</li>
						<li class="span4">
							<div class="proj_block">
								<img src="images/featured_works/landscaping2.png" alt="" />
								<a href="images/featured_works/landscaping2.png" rel="prettyPhoto[portfolio1]"><span class="portfolio_zoom1"></span></a>
								<div class="proj_descr">
									<p>Retaining Wall.</p>
									Retaining Wall.
								</div>
							</div>
						</li>
						<div class="clear"></div>
					</ul>
				</div>
			</div>
			<!--//Recent Gallery-->
			
			<!--Welcome-->
			<div class="wrap welcome_bg">
				<div class="container">
					<div class="welcome_block">
						<p><span>Creative ideas</span> for your garden</p>
						Provide best quality work with a very competitive price. All work guaranteed
					</div>
				</div>
			</div>
			<!--//Welcome-->
			
			<!--planning-->
			<div class="wrap planning">
				<div class="container">
					<div class="row">
						<a class="span3" href="javascript:void(0);">
							<span class="service_block">
								<span class="icon_block">
									<img class="icon1" src="images/icon1.png" />
									<img class="icon1_h" src="images/icon1_h.png" />
								</span>
								<span class="link_title">Consultation</span>
								<span class="service_txt">No work is small for us.  
								We will be on-site and provide a free estimate for all the work.</span>
							</span>
						</a>
						<a class="span3" href="javascript:void(0);">
							<span class="service_block">
								<span class="icon_block">
									<img class="icon1" src="images/icon2.png" />
									<img class="icon1_h" src="images/icon2_h.png" />
								</span>
								<span class="link_title">Landscape Design</span>
								<span class="service_txt">We design landscape architecture that is customized based on your garden landscape</span>
							</span>
						</a>
						<a class="span3" href="javascript:void(0);">
							<span class="service_block">
								<span class="icon_block">
									<img class="icon1" src="images/icon3.png" />
									<img class="icon1_h" src="images/icon3_h.png" />
								</span>
								<span class="link_title">Garden Maintenance</span>
								<span class="service_txt">Our team provide year round garden maintenance.  
								Also provide full maintenance services for commercial companies and builders </span>
							</span>
						</a>
						<a class="span3" href="javascript:void(0);">
							<span class="service_block">
								<span class="icon_block">
									<img class="icon1" src="images/icon4.png" />
									<img class="icon1_h" src="images/icon4_h.png" />
								</span>
								<span class="link_title">Installation</span>
								<span class="service_txt">Our team provide full service for outside system installation including but not limited to
								sprinkler system, retaining wall, patio</span>
							</span>
						</a>
						<div class="clear"></div>
					</div>
				</div>
			</div>
			<!--//planning-->
			
			<!--Latest news-->
			<div class="wrap">
				<div class="container">
					<h2 class="title">testimonials</h2>
					<div id="testim_carousel" class="carousel slide">
						<div class="row carousel-inner">
							<div class="item active">
								<div class="span6 testim_block">
									<div class="testim_block_txt">
										We hired Doan Landscaping company to make a sprinkler system for our home and they did an excellent job. When I broke one of the water sprayer the owner came out and help me to reinstall with no charge. 
										Whenever we need repairment for our backyard we always call Doan's landscaping
									</div>
									<div class="testim_author">Paul Mai</div>
								</div>
								<div class="span6 testim_block">
									<div class="testim_block_txt">
										We, North Ridge HOA community in Lynnwood, hired Doan's Landscaping company to maintain our community common area and they did an excellent work in the past 2 years.  They also provide other services with very competitive prices
									</div>
									<div class="testim_author">North Ridge HOA in Lynnwood, WA</div>
								</div>
								<div class="clear"></div>
							</div>
							<div class="item">
								<div class="span6 testim_block">
									<div class="testim_block_txt">
										We hired Doan Landscaping company to make a sprinkler system for our home and they did an excellent job. When I broke one of the water sprayer the owner came out and help me to reinstall with no charge. 
										Whenever we need repairment for our backyard we always call Doan's landscaping
									</div>
									<div class="testim_author">Paul Mai</div>
								</div>
								<div class="span6 testim_block">
									<div class="testim_block_txt">
										We, North Ridge HOA community in Lynnwood, hired Doan's Landscaping company to maintain our community common area and they did an excellent work in the past 2 years.  They also provide other services with very competitive prices
									</div>
									<div class="testim_author">North Ridge HOA in Lynnwood, WA</div>
								</div>
								<div class="clear"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--Latest news-->

		</div>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="js/jquery.mobile.customized.min.js"></script>
    <script type="text/javascript" src="js/camera.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/superfish.js"></script>
	<script type="text/javascript" src="js/jquery.jcarousel.js"></script>
    <script type="text/javascript" src="js/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" src="js/jquery.tweet.js"></script>
    <script type="text/javascript" src="js/myscript.js"></script>
    <script type="text/javascript">
		\$(document).ready(function(){	
			//Slider
			\$('#camera_wrap_1').camera();
			
			//Testimonials carousel
			\$('#testim_carousel').carousel({
				pause: 'hover'
			});		
			
		});
	</script>


