		<div class="top_line">
			<p class="fleft">Licensed, Bonded & Insured. #DoanLLC920LT.</p>
			<div class="fright follow_us">
				<ul>
					<li><a href="#" class="twitter">Twitter</a></li>
					<li><a href="#" class="rss">Rss</a></li>
					<li><a href="#" class="tumblr">Tumblr</a></li>
					<li><a href="#" class="posterous">Posterous</a></li>
					<li><a href="#" class="google_plus">Google Plus</a></li>
					<li><a href="#" class="facebook">Facebook</a></li> 
					<li><a href="#" class="flickr">Flickr</a></li>
					<li><a href="#" class="vimeo">Vimeo</a></li>
					<li><a href="#" class="dribbble">Dribbble</a></li>
				</ul>
			</div>
			<div class="clear"></div>
		</div>
